### ISSUE TITLE
no scanner show 

### ISSUE THREAD

**Issue by tchach0** [EntySec/Checkmate#1]
when i try to scan i can't find scanner modul

**Comment by enty8080** [comment]
Hello, @tchach0 

I am currently working on fixing such bugs, because this program is on BETA stage.

Thanks for your report, but please, use the issue template next time to describe your issue correctly and more detailed.

In order to fix this, you need to install all scanners manually. Soon, I will add the feature, so they will be installed automatically.

Please, uninstall Fishnet and install it again `tomorrow`, cause I will push stable release. To uninstall it, do this thing:

```
pip3 uninstall fishnet
```

And in MySQL:

```
drop database fishnet;
```

Best regards,
Ivan Nikolsky (@enty8080)

**Comment by tchach0** [comment]
ok thank for ur work

**Comment by enty8080** [comment]
Hello @tchach0

I placed all plugins inside Fishnet, so now, all scanners should appear in projects menu (*projects* -> *open* -> *project name* -> *execute*). Select scanner(s) and click on `execute`. I also added an option to scan custom networks (external if you want to), so now you can also specify them in the same place.

I hope you'll enjoy using this tool.

P.S. I also need to mention that before installing new version of Fishnet you should fully troubleshoot from the current state (drop database, uninstall previous version of Fishnet (`pip3 uninstall fishnet`), uninstall `pex` (`pip3 uninstall pex`), clean `~/.fishnet/config.yml` in case if you have set your database credentials). Then, if you follow these steps, Fishnet should start successfully.

Yours sincerely,
Ivan Nikolsky (@enty8080)

**Comment by tchach0** [comment]
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /bin/sh: 1: mysql_config: not found
      /bin/sh: 1: mariadb_config: not found
      /bin/sh: 1: mysql_config: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ya8rdteh/mysqlclient_2d283f1406f74dfcb226ea1cc547abc9/setup.py", line 15, in <module>
          metadata, options = get_config()
        File "/tmp/pip-install-ya8rdteh/mysqlclient_2d283f1406f74dfcb226ea1cc547abc9/setup_posix.py", line 70, in get_config
          libs = mysql_config("libs")
        File "/tmp/pip-install-ya8rdteh/mysqlclient_2d283f1406f74dfcb226ea1cc547abc9/setup_posix.py", line 31, in mysql_config
          raise OSError("{} not found".format(_mysql_config_path))
      OSError: mysql_config not found
      mysql_config --version
      mariadb_config --version
      mysql_config --libs
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by enty8080** [comment]
@tchach0 You need to follow instructions from wiki. Install `mysql` using `apt` or other package manager.
